#PYTORCH_NO_CUDA_MEMORY_CACHING=1 ORT_LT_DUMP_ATEN_OP_HISTORY=1 /usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-eager python bert-exp.py --mode=eager
#PYTORCH_NO_CUDA_MEMORY_CACHING=1 ORT_LT_DUMP_ATEN_OP_HISTORY=1 /usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-dynamo-aten python bert-exp.py --mode=aten
#PYTORCH_NO_CUDA_MEMORY_CACHING=1 ORT_LT_DUMP_ATEN_OP_HISTORY=1 /usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-dynamo-ort python bert-exp.py --mode=ort
#PYTORCH_NO_CUDA_MEMORY_CACHING=1 ORT_LT_DUMP_ATEN_OP_HISTORY=1 /usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-dynamo-nvfuser python bert-exp.py --mode=nvfuser
#PYTORCH_NO_CUDA_MEMORY_CACHING=1 ORT_LT_DUMP_ATEN_OP_HISTORY=1 /usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-ortmodule python bert-exp.py --mode=ortmodule

/usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-cache-eager-nploss python bert-exp.py --mode=eager
#/usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-cache-dynamo-aten python bert-exp.py --mode=aten
#/usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-cache-dynamo-nvfuser python bert-exp.py --mode=nvfuser
/usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-cache-dynamo-ort-new-wrap-nploss python bert-exp.py --mode=ort
/usr/local/cuda-11.3/nsight-systems-2021.1.3/bin/nsys profile --trace cuda,nvtx,osrt,cublas,cudnn --force-overwrite true -s cpu -b fp --cudabacktrace memory --cuda-memory-usage true --stats false --sampling-period 2000000 -o bert-cache-ortmodule-nploss python bert-exp.py --mode=ortmodule