name: periodic

on:
  schedule:
    - cron: 45 0,4,8,12,16,20 * * *
  push:
    tags:
      - ciflow/periodic/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-xenial-cuda10_2-py3-gcc7-slow-gradcheck-build:
    if: false # https://github.com/pytorch/pytorch/issues/80314
    name: linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck
      docker-image-name: pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7

  linux-xenial-cuda10_2-py3-gcc7-slow-gradcheck-test:
    if: false # https://github.com/pytorch/pytorch/issues/80314
    name: linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-xenial-cuda10_2-py3-gcc7-slow-gradcheck-build
    with:
      build-environment: linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck
      docker-image: ${{ needs.linux-xenial-cuda10_2-py3-gcc7-slow-gradcheck-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" },
        ]}

  linux-focal-rocm5_1-py3_7-slow-build:
    name: linux-focal-rocm5.1-py3.7-slow
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-rocm5.1-py3.7
      docker-image-name: pytorch-linux-focal-rocm5.1-py3.7

  linux-focal-rocm5_1-py3_7-slow-test:
    name: linux-focal-rocm5.1-py3.7-slow
    uses: ./.github/workflows/_rocm-test.yml
    needs: linux-focal-rocm5_1-py3_7-slow-build
    with:
      build-environment: linux-focal-rocm5.1-py3.7
      docker-image: ${{ needs.linux-focal-rocm5_1-py3_7-slow-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "slow", shard: 1, num_shards: 1, runner: "linux.rocm.gpu" },
        ]}
    secrets:
      AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
      AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}

  linux-focal-rocm5_1-py3_7-distributed-build:
    name: linux-focal-rocm5.1-py3.7-distributed
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-rocm5.1-py3.7
      docker-image-name: pytorch-linux-focal-rocm5.1-py3.7

  linux-focal-rocm5_1-py3_7-distributed-test:
    if: false # https://github.com/pytorch/pytorch/issues/80529
    name: linux-focal-rocm5.1-py3.7-distributed
    uses: ./.github/workflows/_rocm-test.yml
    needs: linux-focal-rocm5_1-py3_7-distributed-build
    with:
      build-environment: linux-focal-rocm5.1-py3.7
      docker-image: ${{ needs.linux-focal-rocm5_1-py3_7-distributed-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "distributed", shard: 1, num_shards: 2, runner: "linux.rocm.gpu" },
          { config: "distributed", shard: 2, num_shards: 2, runner: "linux.rocm.gpu" },
        ]}
    secrets:
      AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
      AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}

  linux-bionic-cuda10_2-py3_9-gcc7-build:
    name: linux-bionic-cuda10.2-py3.9-gcc7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda10.2-py3.9-gcc7
      docker-image-name: pytorch-linux-bionic-cuda10.2-cudnn7-py3.9-gcc7

  linux-bionic-cuda10_2-py3_9-gcc7-test:
    name: linux-bionic-cuda10.2-py3.9-gcc7
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda10_2-py3_9-gcc7-build
    with:
      build-environment: linux-bionic-cuda10.2-py3.9-gcc7
      docker-image: ${{ needs.linux-bionic-cuda10_2-py3_9-gcc7-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "multigpu", shard: 1, num_shards: 1, runner: "linux.16xlarge.nvidia.gpu" },
        ]}

  linux-bionic-cuda11_6-py3_7-gcc7-debug-build:
    name: linux-bionic-cuda11.6-py3.7-gcc7-debug
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.6-py3.7-gcc7-debug
      docker-image-name: pytorch-linux-bionic-cuda11.6-cudnn8-py3-gcc7
      build-with-debug: true

  linux-bionic-cuda11_6-py3_7-gcc7-debug-test:
    name: linux-bionic-cuda11.6-py3.7-gcc7-debug
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_6-py3_7-gcc7-debug-build
    with:
      build-environment: linux-bionic-cuda11.6-py3.7-gcc7-debug
      docker-image: ${{ needs.linux-bionic-cuda11_6-py3_7-gcc7-debug-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
        ]}

  ios-12-5-1-x86-64-coreml:
    name: ios-12-5-1-x86-64-coreml
    uses: ./.github/workflows/_ios-build-test.yml
    with:
      build-environment: ios-12-5-1-x86-64-coreml
      ios-platform: SIMULATOR
      ios-arch: x86_64
    secrets:
      IOS_CERT_KEY_2022: ${{ secrets.IOS_CERT_KEY_2022 }}
      IOS_CERT_SECRET: ${{ secrets.IOS_CERT_SECRET}}
      IOS_DEV_TEAM_ID: ${{ secrets.IOS_DEV_TEAM_ID}}
      IOS_SIGN_KEY_2022: ${{ secrets.IOS_SIGN_KEY_2022 }}

  ios-12-5-1-arm64:
    name: ios-12-5-1-arm64
    uses: ./.github/workflows/_ios-build-test.yml
    with:
      build-environment: ios-12-5-1-arm64
      ios-platform: OS
      ios-arch: arm64
    secrets:
      IOS_CERT_KEY_2022: ${{ secrets.IOS_CERT_KEY_2022 }}
      IOS_CERT_SECRET: ${{ secrets.IOS_CERT_SECRET}}
      IOS_DEV_TEAM_ID: ${{ secrets.IOS_DEV_TEAM_ID}}
      IOS_SIGN_KEY_2022: ${{ secrets.IOS_SIGN_KEY_2022 }}

  ios-12-5-1-arm64-coreml:
    name: ios-12-5-1-arm64-coreml
    uses: ./.github/workflows/_ios-build-test.yml
    with:
      build-environment: ios-12-5-1-arm64-coreml
      ios-platform: OS
      ios-arch: arm64
    secrets:
      IOS_CERT_KEY_2022: ${{ secrets.IOS_CERT_KEY_2022 }}
      IOS_CERT_SECRET: ${{ secrets.IOS_CERT_SECRET}}
      IOS_DEV_TEAM_ID: ${{ secrets.IOS_DEV_TEAM_ID}}
      IOS_SIGN_KEY_2022: ${{ secrets.IOS_SIGN_KEY_2022 }}

  ios-12-5-1-arm64-custom-ops:
    name: ios-12-5-1-arm64-custom-ops
    uses: ./.github/workflows/_ios-build-test.yml
    with:
      build-environment: ios-12-5-1-arm64-custom-ops
      ios-platform: OS
      ios-arch: arm64
    secrets:
      IOS_CERT_KEY_2022: ${{ secrets.IOS_CERT_KEY_2022 }}
      IOS_CERT_SECRET: ${{ secrets.IOS_CERT_SECRET}}
      IOS_DEV_TEAM_ID: ${{ secrets.IOS_DEV_TEAM_ID}}
      IOS_SIGN_KEY_2022: ${{ secrets.IOS_SIGN_KEY_2022 }}

  ios-12-5-1-arm64-metal:
    name: ios-12-5-1-arm64-metal
    uses: ./.github/workflows/_ios-build-test.yml
    with:
      build-environment: ios-12-5-1-arm64-metal
      ios-platform: OS
      ios-arch: arm64
    secrets:
      IOS_CERT_KEY_2022: ${{ secrets.IOS_CERT_KEY_2022 }}
      IOS_CERT_SECRET: ${{ secrets.IOS_CERT_SECRET}}
      IOS_DEV_TEAM_ID: ${{ secrets.IOS_DEV_TEAM_ID}}
      IOS_SIGN_KEY_2022: ${{ secrets.IOS_SIGN_KEY_2022 }}

  buck-build-test:
    name: buck-build-test
    uses: ./.github/workflows/_buck-build-test.yml
