name: weekly

on:
  schedule:
    # Mondays at 7:37am UTC = 12:27am PST
    # Choose a random time near midnight PST because it may be delayed if there are high loads
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: 37 7 * * 1
  workflow_dispatch:

jobs:
  update-commit-hash:
    runs-on: ubuntu-latest
    environment: update-commit-hash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update-xla-commit-hash
        continue-on-error: true
        uses: ./.github/actions/update-commit-hash
        with:
          repo-name: xla
          branch: master
          updatebot-token: ${{ secrets.UPDATEBOT_TOKEN }}
          pytorchbot-token: ${{ secrets.GH_PYTORCHBOT_TOKEN }}
      - name: update-triton-commit-hash
        uses: ./.github/actions/update-commit-hash
        with:
          repo-owner: openai
          repo-name: triton
          branch: main
          pin-folder: .ci/docker/ci_commit_pins
          updatebot-token: ${{ secrets.UPDATEBOT_TOKEN }}
          pytorchbot-token: ${{ secrets.GH_PYTORCHBOT_TOKEN }}
